version: "3"

services:
  frontend:
    restart: always
    build: .
    environment:
      VIRTUAL_PORT: "3000"
      VIRTUAL_HOST: "justmark0.me"
      LETSENCRYPT_HOST: "justmark0.me"
      LETSENCRYPT_EMAIL: "developer@justmark0.me"
    networks:
      - web

networks:
  web: # external network for hostname access
    external:
      name: web