name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and start docker image
    - run: docker-compose -f docker-compose.deploy.yml -p justmark0me_frontend stop
    - run: docker-compose -f docker-compose.deploy.yml -p justmark0me_frontend rm -f
    - run: docker network create web
    - run: docker-compose -f docker-compose.deploy.yml -p justmark0me_frontend up --build -d
