name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: actions/checkout@v2
      - name: Build and start docker image
        uses: actions/checkout@v2

      - name: Stop previous containers
        run: docker stop justmark0me_frontend
        continue-on-error: true

      - name: Remove old container
        run: docker rm -f justmark0me_frontend
        continue-on-error: true

      - name: Build container
        run: |
          docker build -t justmark0me_frontend -f Dockerfile .  &&
          docker tag justmark0me_frontend justmark0me_frontend:latest

      - name: Run service
        run: |
          docker run --detach \
          --name justmark0me_frontend \
          --env "VIRTUAL_PORT=3000" \
          --env "VIRTUAL_HOST=justmark0.me" \
          --env "LETSENCRYPT_HOST=justmark0.me" \
          --env "LETSENCRYPT_EMAIL=developer@justmark0.me" \
          justmark0me_frontend:latest 
